window.invoke_exception = (message) => alert(message);